services:
  - type: web
    name: myntra-review-app
    env: python
    buildCommand: ./render-build.sh && pip install -r requirements.txt
    startCommand: streamlit run app.py
    envVars:
      - key: PORT
        value: 10000
